# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin-stdlib = "1.9.22"
jackson-databind = "2.13.4.1"
guava = "31.1-jre"
guice = "5.1.0"
authlib = "1.5.21"
dataformat-hocon = "2.1-SNAPSHOT"
netty = "4.1.74.Final"
fastutil = "8.5.6"
adventure-api = "4.10.1"
adventure-platform-api = "4.1.0"
adventure-minimessage = "4.10.0"
commons-lang3 = "3.12.0"
jetbrains-annotations = "23.0.0"
junit-jupiter = "5.8.2"
reflections = "0.10.2"

# Spigot Impl dependencies
papermc = "1.20.4-R0.1-SNAPSHOT"
bstats-bukkit = "3.0.0"
item-nbt-api = "2.11.3"
nbt-data-api = "2.11.3"

[libraries]
org-jetbrains-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin-stdlib" }
com-fasterxml-jackson-core-jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-databind" }
com-google-guava-guava = { module = "com.google.guava:guava", version.ref = "guava" }
com-google-inject-guice = { module = "com.google.inject:guice", version.ref = "guice" }
com-mojang-authlib = { module = "com.mojang:authlib", version.ref = "authlib" }
com-wolfyscript-jackson-dataformat-hocon = { module = "com.wolfyscript:jackson-dataformat-hocon", version.ref = "dataformat-hocon" }
io-netty-netty-all = { module = "io.netty:netty-all", version.ref = "netty" }
it-unimi-dsi-fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
net-kyori-adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure-api" }
net-kyori-adventure-platform-api = { module = "net.kyori:adventure-platform-api", version.ref = "adventure-platform-api" }
net-kyori-adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure-minimessage" }
org-apache-commons-commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
org-jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
org-junit-jupiter-junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
org-reflections-reflections = { module = "org.reflections:reflections", version.ref = "reflections" }

# Spigot Impl dependencies
io-papermc-paper = { module = "io.papermc.paper:paper-api", version.ref = "papermc" }
org-bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats-bukkit" }
de-tr7zw-item-nbt-api = { module = "de.tr7zw:item-nbt-api", version.ref = "item-nbt-api" }
de-tr7zw-nbt-data-api = { module = "de.tr7zw:nbt-data-api", version.ref = "nbt-data-api" }
net-kyori-adventure-platform-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platform-api" }
